### ISSUE TITLE
Over bearing

### ISSUE THREAD

**Issue by TyHen** [GreatOrator/FallCraft-Map#31]
Edit: The title is supposed to be Over bearing Mobs!
Greetings y'all.

I found something awhile ago but pressed through it a bit, but it has surfaced to a point that I give up from time to time. When you load into the game, the game difficulty is at peaceful so there are no mobs. I changed it to easy and the mobs were so over bearing that I could not even cross the first bridge. I mean hundreds of mobs even on easy. Is it possible to turn down the spawn rate just a tad? I know that Lycanties Mobs can over rule a lot of that because I have seen it in past modpacks.

Thanks again y'all appreciate the hard work you guys do.
From a fellow (very) beginner modder,
TyHen

**Comment by teagan75** [comment]
First off. Make sure you are on version 0.12.5 that map should not be on peaceful. 

Secondly, we have been trying to scale back mobs however because it’s a wasteland biome doesn’t help the situation. I keep tweaking the mob spawn count and it makes no difference.  Have been placing magnum torches along the way on roads and POI only to “thin the herds” but that map isn’t out yet.

**Comment by TyHen** [comment]
That is fully understandable, but I know that you will find a solution.

**Comment by TyHen** [comment]
If you are aware of this then I will close it thanks Teagan.
